### ISSUE TITLE
how to put inside folder if the folder path contain space

### ISSUE THREAD

**Issue by kucingkembar** [josephcappadona/m3u8downloader#5]
hi sorry for my bad english,
i have problem, 
if i doing this:
`downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o E:\TestUrl\Test.mp4 --tempdir E:\TestUrl\`
it work,
but if:
`downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o E:\Test Url\Test.mp4 --tempdir E:\Test Url\`
it not work,
i tried to add " like this:
`downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o "E:\Test Url\Test.mp4" --tempdir "E:\Test Url\"`
it still not work, please help

**Comment by josephcappadona** [comment]
I'm not an expert on Windows, but try
```bash
downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o E:\"Test Url"\Test.mp4 --tempdir E:\"Test Url"\
```

Does that work?

**Comment by kucingkembar** [comment]
m3u8downloader: error: unrecognized arguments: Url"\Test.mp4 --tempdir E:\"Test Url"\

**Comment by josephcappadona** [comment]
ChatGPT suggests this:

Try escaping the spaces in your file path using the caret symbol ^ in Windows command line. Your command would look like this:

```bash
downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o E:\Test^ Url\Test.mp4 --tempdir E:\Test^ Url\
```

Alternatively, replace the spaces with %20, which is the URL encoding for a space character:
```bash
downloadm3u8 https://example.com/123-456-abc/video.m3u8 -o E:\Test%20Url\Test.mp4 --tempdir E:\Test%20Url\
```

**Comment by kucingkembar** [comment]
the ^ do not work,
but the %20 working,
i just need add .replace(" ","%20") in the path,
thank you mate

**Comment by kucingkembar** [comment]
additional result :
the result folder from `E:\Test%20Url\Test.mp4`, 
literally `E:\Test%20Url\Test.mp4`
not equal to `E:\Test Url\Test.mp4`

**Comment by kucingkembar** [comment]
after i do some reserach, turn out, the problem in my side,
at `--tempdir "E:\Test Url\"`, the` Url\"`, or more correctly `\"` count as escape character,
so to make it work, you must type path without `\"` at the end line,
so it became like this `--tempdir "E:\Test Url"`
at this point, i am really sorry

**Comment by josephcappadona** [comment]
No worries at all, glad you got it figured out!
